# Generated by Django 2.2.5 on 2019-09-24 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published at:'),
            preserve_default=False,
        ),
    ]
