# Generated by Django 2.2.5 on 2019-09-25 15:32

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190924_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(upload_to=posts.models.user_directory_path),
        ),
    ]
