# Generated by Django 2.2.5 on 2019-09-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_album_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='userid',
        ),
    ]
