# Generated by Django 2.2.5 on 2019-10-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190927_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='postid',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Published at:'),
        ),
    ]
