# Generated by Django 2.2.5 on 2019-10-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20191006_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visible',
        ),
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default='False', verbose_name='Hidden post'),
        ),
    ]
