# Generated by Django 2.2.5 on 2019-10-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190926_1121'),
        ('posts', '0011_auto_20191006_1221'),
    ]

    operations = [
    ]
