# Generated by Django 2.2.6 on 2020-01-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_merge_20191031_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='postid',
        ),
        migrations.AddField(
            model_name='album',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(upload_to=posts.models.user_directory_path),
        ),
    ]
